alias setjdk6='export JAVA_HOME=$(/usr/libexec/java_home -v 1.6); export PATH=$JAVA_HOME/bin:$PATH'
#alias setjdk7='export JAVA_HOME=$(/usr/libexec/java_home -v 1.7); export JAVA_OPTS="-Xbootclasspath/a:/Users/kgroshev/projects/nashorn-backport/dist/nashorn.jar" export PATH=$JAVA_HOME/bin:$PATH'
alias setjdk7='export JAVA_HOME=$(/usr/libexec/java_home -v 1.7); export PATH=$JAVA_HOME/bin:$PATH'
alias setjdk8='export JAVA_HOME=$(/usr/libexec/java_home -v 1.8); export PATH=$JAVA_HOME/bin:$PATH'
alias setjdk9='export JAVA_HOME=$(/usr/libexec/java_home -v 9); export PATH=$JAVA_HOME/bin:$PATH'
alias setjdk10='export JAVA_HOME=$(/usr/libexec/java_home -v 10); export PATH=$JAVA_HOME/bin:$PATH'
